/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateAttendeeArgs } from "./CreateAttendeeArgs";
import { UpdateAttendeeArgs } from "./UpdateAttendeeArgs";
import { DeleteAttendeeArgs } from "./DeleteAttendeeArgs";
import { AttendeeCountArgs } from "./AttendeeCountArgs";
import { AttendeeFindManyArgs } from "./AttendeeFindManyArgs";
import { AttendeeFindUniqueArgs } from "./AttendeeFindUniqueArgs";
import { Attendee } from "./Attendee";
import { TicketFindManyArgs } from "../../ticket/base/TicketFindManyArgs";
import { Ticket } from "../../ticket/base/Ticket";
import { Event } from "../../event/base/Event";
import { AttendeeService } from "../attendee.service";
@graphql.Resolver(() => Attendee)
export class AttendeeResolverBase {
  constructor(protected readonly service: AttendeeService) {}

  async _attendeesMeta(
    @graphql.Args() args: AttendeeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Attendee])
  async attendees(
    @graphql.Args() args: AttendeeFindManyArgs
  ): Promise<Attendee[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => Attendee, { nullable: true })
  async attendee(
    @graphql.Args() args: AttendeeFindUniqueArgs
  ): Promise<Attendee | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Attendee)
  async createAttendee(
    @graphql.Args() args: CreateAttendeeArgs
  ): Promise<Attendee> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        event: {
          connect: args.data.event,
        },
      },
    });
  }

  @graphql.Mutation(() => Attendee)
  async updateAttendee(
    @graphql.Args() args: UpdateAttendeeArgs
  ): Promise<Attendee | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          event: {
            connect: args.data.event,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Attendee)
  async deleteAttendee(
    @graphql.Args() args: DeleteAttendeeArgs
  ): Promise<Attendee | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Ticket], { name: "tikets" })
  async resolveFieldTikets(
    @graphql.Parent() parent: Attendee,
    @graphql.Args() args: TicketFindManyArgs
  ): Promise<Ticket[]> {
    const results = await this.service.findTikets(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Event, {
    nullable: true,
    name: "event",
  })
  async resolveFieldEvent(
    @graphql.Parent() parent: Attendee
  ): Promise<Event | null> {
    const result = await this.service.getEvent(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
