/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AttendeeService } from "../attendee.service";
import { AttendeeCreateInput } from "./AttendeeCreateInput";
import { AttendeeWhereInput } from "./AttendeeWhereInput";
import { AttendeeWhereUniqueInput } from "./AttendeeWhereUniqueInput";
import { AttendeeFindManyArgs } from "./AttendeeFindManyArgs";
import { AttendeeUpdateInput } from "./AttendeeUpdateInput";
import { Attendee } from "./Attendee";
import { TicketFindManyArgs } from "../../ticket/base/TicketFindManyArgs";
import { Ticket } from "../../ticket/base/Ticket";
import { TicketWhereUniqueInput } from "../../ticket/base/TicketWhereUniqueInput";

export class AttendeeControllerBase {
  constructor(protected readonly service: AttendeeService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Attendee })
  async create(@common.Body() data: AttendeeCreateInput): Promise<Attendee> {
    return await this.service.create({
      data: {
        ...data,

        event: {
          connect: data.event,
        },
      },
      select: {
        email: true,

        event: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Attendee] })
  @ApiNestedQuery(AttendeeFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Attendee[]> {
    const args = plainToClass(AttendeeFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        email: true,

        event: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Attendee })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: AttendeeWhereUniqueInput
  ): Promise<Attendee | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        email: true,

        event: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Attendee })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: AttendeeWhereUniqueInput,
    @common.Body() data: AttendeeUpdateInput
  ): Promise<Attendee | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          event: {
            connect: data.event,
          },
        },
        select: {
          email: true,

          event: {
            select: {
              id: true,
            },
          },

          id: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Attendee })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: AttendeeWhereUniqueInput
  ): Promise<Attendee | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          email: true,

          event: {
            select: {
              id: true,
            },
          },

          id: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/tikets")
  @ApiNestedQuery(TicketFindManyArgs)
  async findManyTikets(
    @common.Req() request: Request,
    @common.Param() params: AttendeeWhereUniqueInput
  ): Promise<Ticket[]> {
    const query = plainToClass(TicketFindManyArgs, request.query);
    const results = await this.service.findTikets(params.id, {
      ...query,
      select: {
        attendee: {
          select: {
            id: true,
          },
        },

        id: true,
        ticketType: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/tikets")
  async connectTikets(
    @common.Param() params: AttendeeWhereUniqueInput,
    @common.Body() body: TicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tikets: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/tikets")
  async updateTikets(
    @common.Param() params: AttendeeWhereUniqueInput,
    @common.Body() body: TicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tikets: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/tikets")
  async disconnectTikets(
    @common.Param() params: AttendeeWhereUniqueInput,
    @common.Body() body: TicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tikets: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
